name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master for build
      uses: actions/checkout@v3
    - name: Upload build as artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: ./public/
    - name: Checkout Github Pages
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: 'gh-pages'
    - name: Download most recent build
      uses: actions/download-artifact@master
      with:
        name: public
        path: ./
    - name: Commit changes
      run: |
        git config user.email "bot@rodent.club"
        git config user.name "ratbot"
        git add -A
        git commit -m "Automated publish"
        git push
